import pandas as pd
import matplotlib.pyplot as plt
from fpdf import FPDF
from datetime import datetime, timedelta

class MayFlyPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.image('ba_logo.png', 10, 8, 33)
        self.cell(0, 10, 'British Airways | MayFly Load Summary', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 10, f'Generated: {datetime.now().strftime("%d %b %Y %H:%M")}', 0, 1, 'C')
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Confidential © 2025 | Generated by Nathaniel Claxton', 0, 0, 'C')

    def flight_table(self, flights):
        self.set_font('Arial', 'B', 9)
        self.set_fill_color(200, 200, 200)
        self.cell(25, 8, 'Flight No', 1, 0, 'C', 1)
        self.cell(30, 8, 'Route', 1, 0, 'C', 1)
        self.cell(30, 8, 'ETD', 1, 0, 'C', 1)
        self.cell(30, 8, 'Aircraft Reg', 1, 0, 'C', 1)
        self.cell(30, 8, 'Status', 1, 0, 'C', 1)
        self.cell(25, 8, 'Load %', 1, 1, 'C', 1)

        self.set_font('Arial', '', 9)

        for flight in flights:
            load = flight['load_factor']
            # Color logic
            if load >= 91:
                self.set_fill_color(255, 0, 0)  # Red
            elif 70 <= load <= 90:
                self.set_fill_color(255, 165, 0)  # Amber
            else:
                self.set_fill_color(255, 255, 255)  # White

            self.cell(25, 8, flight['flight_no'], 1, 0, 'C', 1)
            self.cell(30, 8, flight['route'], 1, 0, 'C', 1)

            # ETD fix: convert to Zulu + add 1hr
            try:
                time_obj = datetime.strptime(flight['etd'], "%H:%M")
                zulu_plus_one = (time_obj + timedelta(hours=1)).strftime("%H:%M")
                self.cell(30, 8, zulu_plus_one, 1, 0, 'C', 1)
            except:
                self.cell(30, 8, flight['etd'], 1, 0, 'C', 1)

            self.cell(30, 8, flight['aircraft_reg'], 1, 0, 'C', 1)
            self.cell(30, 8, flight['status'], 1, 0, 'C', 1)
            self.cell(25, 8, f"{load}%", 1, 1, 'C', 1)

def generate_pdf(flight_data, output_file='MayFly_Report.pdf'):
    pdf = MayFlyPDF()
    pdf.add_page()
    pdf.flight_table(flight_data)
    pdf.output(output_file)
