import streamlit as st
import pandas as pd
import re
from datetime import datetime, timedelta
from fpdf import FPDF
import hashlib
import pytz

# === Secure Password Protection ===
def get_hashed_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

correct_password_hash = get_hashed_password("MayFly2025!")

def check_password():
    def password_entered():
        entered_password_hash = get_hashed_password(st.session_state["password"])
        if entered_password_hash == correct_password_hash:
            st.session_state["password_correct"] = True
            del st.session_state["password"]
        else:
            st.session_state["password_correct"] = False

    if "password_correct" not in st.session_state:
        st.text_input("Enter password:", type="password", on_change=password_entered, key="password")
        return False
    elif not st.session_state["password_correct"]:
        st.text_input("Enter password:", type="password", on_change=password_entered, key="password")
        st.error("😕 Password incorrect. Try again.")
        return False
    else:
        return True

if not check_password():
    st.stop()

# === Domestic route filter ===
DOMESTIC_ROUTES = ["LHRABZ", "LHRINV", "LHRGLA", "LHREDI", "LHRBHD", "LHRNCL", "LHRJER", "LHRMAN", "LHRBFS"]

# === Main App ===
BA_BLUE = (0, 32, 91)
LIGHT_RED = (255, 204, 204)
AMBER = (255, 229, 153)

class BA_PDF(FPDF):
    def __init__(self, date_str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.date_str = date_str

    def header(self):
        self.set_fill_color(*BA_BLUE)
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 14)
        self.cell(0, 10, f'MayFly {self.date_str} - British Airways', ln=True, align='C', fill=True)
        self.ln(5)

    def footer(self):
        self.set_y(-12)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100)
        self.cell(0, 8, 'Confidential © 2025  |  Generated by British Airways', 0, 0, 'C')

    def flight_table(self, data):
        headers = ['Flight No', 'Aircraft', 'Route', 'ETD (Zulu)', 'Conformance', 'Load']
        widths = [30, 25, 30, 30, 30, 20]

        self.set_font('Arial', 'B', 8.5)
        self.set_fill_color(*BA_BLUE)
        self.set_text_color(255, 255, 255)
        for i in range(len(headers)):
            self.cell(widths[i], 6, headers[i], 1, 0, 'C', True)
        self.ln()

        self.set_font('Arial', '', 7.5)
        self.set_text_color(0)
        for _, row in data.iterrows():
            for i, key in enumerate(["Flight Number", "Aircraft Type", "Route", "ETD", "Conformance Time", "Load Factor"]):
                fill = False
                if key == "Load Factor":
                    load = int(row["Load Factor"].rstrip('%'))
                    if load > 91:
                        self.set_fill_color(*LIGHT_RED)
                        fill = True
                    elif 70 <= load <= 90:
                        self.set_fill_color(*AMBER)
                        fill = True
                self.cell(widths[i], 6, row[key], 1, 0, 'C', fill)
            self.ln()

def parse_txt(file_content, filter_type):
    lines = file_content.strip().split('\n')
    flights = []
    utc_tz = pytz.utc

    i = 0
    while i < len(lines):
        if lines[i].startswith("BA"):
            try:
                flight_no = lines[i].strip()
                aircraft_type = lines[i+2].strip()
                route = lines[i+3].strip()

                std_match = re.search(r"STD: \d{2} \w+ - (\d{2}:\d{2})z", lines[i+4])
                load_match = re.search(r"(\d{1,3})%Status", lines[i+8])

                if std_match and load_match:
                    etd_utc_str = std_match.group(1)
                    load = int(load_match.group(1))

                    etd_utc = datetime.strptime(etd_utc_str, "%H:%M")
                    etd_utc = utc_tz.localize(etd_utc)

                    conformance_time = (etd_utc - timedelta(minutes=35)).strftime("%H:%M")

                    flights.append({
                        "Flight Number": flight_no,
                        "Aircraft Type": aircraft_type,
                        "Route": route,
                        "ETD": etd_utc.strftime("%H:%M") + "z",
                        "ETD Local": etd_utc.strftime("%H:%M"),
                        "Conformance Time": conformance_time,
                        "Load Factor": f"{load}%",
                        "Load Factor Numeric": load
                    })
            except Exception:
                pass
        i += 1

    df = pd.DataFrame(flights)

    if not df.empty:
        if filter_type == "Flights above 90%":
            df = df[df["Load Factor Numeric"] >= 90]
        elif filter_type == "Domestic":
            df = df[df["Route"].isin(DOMESTIC_ROUTES)]
        df = df.sort_values(by="ETD Local")

    return df

st.set_page_config(page_title="British Airways MayFly Generator", page_icon="")
st.title("British Airways MayFly PDF Generator")

selected_date = st.date_input("Select MayFly Date", datetime.today())
date_str = selected_date.strftime("%d %B")

filter_option = st.radio("Choose Filter", ["All Flights", "Flights above 90%", "Domestic"])

st.markdown("### Paste your MayFly data below")
text_input = st.text_area("Paste .txt contents here")

if text_input:
    flights_df = parse_txt(text_input, filter_option)

    if not flights_df.empty:
        st.success(f"Processed {len(flights_df)} flights ({filter_option}).")

        pdf = BA_PDF(date_str, orientation='P', unit='mm', format='A4')
        pdf.set_auto_page_break(auto=True, margin=10)
        pdf.add_page()
        pdf.flight_table(flights_df)

        pdf_output_path = "/tmp/BA_MayFly_Output.pdf"
        pdf.output(pdf_output_path)

        with open(pdf_output_path, "rb") as file:
            st.download_button(
                label="Download MayFly PDF",
                data=file,
                file_name=f"BA_MayFly_{date_str.replace(' ', '_')}.pdf",
                mime="application/pdf"
            )

        st.info("Footer: Confidential © 2025 | British Airways")
    else:
        st.error("No valid flights found with current filter. Please check your pasted data.")
